### ISSUE TITLE
Mega-issue tracking all of the problems with running the "Fetal Brain MRI Reconstruction Pipeline

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_ultron_backEnd#559]
The "Fetal Brain MRI Reconstruction Pipeline" is an important pipeline we run at BCH.

- https://chrisproject.org/blog/2023/11/14/fetal-reconstruction-pipeline
- https://github.com/FNNDSC/Fetal_Brain_MRI_Reconstruction_Pipeline

It works on our internal deployment of CUBE, but is suboptimal.

## Feature Requests

This issue is an aggregation of all feature requests which would improve how the pipeline is used.

- [ ] It should be possible to set what compute environment is preferred for pipings of a pipeline.
- [ ] When creating a workflow of a pipeline, `cpu_limit`, `gpu_limit`, and `memory_limit` should be somehow configurable.

## UI requests

- [ ] Make it easier to select some (but not all) series of a study as the input for a new feed.

## Deployment Considerations

Container "cold boot" problem: pulling container images which have large files (such as ML weights) takes a long time. Possible solutions:

- [ ] Use SLURM+E3, which uses Apptainer images from the NFS
- [ ] Set up an internal container registry cache for Kubernetes
- [ ] Confine the jobs to a single machine

**Comment by rudolphpienaar** [comment]
Another issue:
* End-to-End, i.e. DICOM-to-DICOM and transmission of final recon to clinical PACS
